import localFont from "next/font/local";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import "./globals.css";

import { authConfig } from "./lib/auth";
import { Procted } from "./components/Procted";
import { redirect } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <Procted session={session}>{children}</Procted>
      </body>
    </html>
  );
}
